In [1]:
import numpy as np
from Data import Numbers
from nn import Network

In [2]:
# Data structure for accessing mnist data
n = Numbers("./Data/mnist.pkl.gz")

In [3]:
# Initial network for max pooling to 28 inputs instead of 784
X = np.array(n.train[0])
net1 = Network([28,28,28,10])
X.shape

(50000, 784)

In [4]:
for j in range (28):
    temp = X[1][28*j:28*j+28]
    print("%s:\tlen: %d" % (str(temp),len(temp)))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]:	len: 28
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]:	len: 28
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]:	len: 28
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]:	len: 28
[ 0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.19921875  0.62109375  0.98828125  0.62109375  0.1953125   0.
  0.          0.          0.          0.          0.          0.          0.        ]:	len: 28
[ 0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.          0.
  0.1875      0.9296875 

In [5]:
#Max pooled input data
X1 = np.zeros((50000,28))
for i in range(50000):
    for j in range(28):
        X1[i][j] = sum(X[i][28*j:28*j+28])
        
X1

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [6]:
# Adjust labels to fit the 10x1 output requirement
y1 = np.zeros((50000,10))
for i in range(50000):
    y1[i][n.train[1][i]] = 1
    
y1.shape

(50000, 10)

In [7]:
X1[1]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  2.625     ,
        4.99609375,  6.14453125,  7.671875  ,  9.30078125,  8.31640625,
        6.8125    ,  6.44921875,  5.83984375,  5.171875  ,  5.25390625,
        5.23046875,  4.62890625,  4.8671875 ,  4.375     ,  5.19921875,
        7.796875  ,  9.24609375,  7.2890625 ,  4.25      ,  0.        ,
        0.        ,  0.        ,  0.        ])

In [10]:
net1.SGD_train(zip(X1,y1),10,0.1)

Epoch    1: Train    0.00000


In [33]:
#Test points using training data
print("Evaluating on test points")
randomTests = [[np.array(X1[i]).reshape(len(X1[i]),1),np.array(y1[i]).reshape(len(y1[i]),1)] for i in np.random.randint(0,50000,size=20)]
randomTests

Evaluating on test points


[[array([[ 0.        ],
         [ 0.        ],
         [ 0.        ],
         [ 0.        ],
         [ 2.2421875 ],
         [ 4.984375  ],
         [ 8.22265625],
         [ 9.46484375],
         [ 7.97265625],
         [ 4.234375  ],
         [ 2.9921875 ],
         [ 2.73828125],
         [ 3.23828125],
         [ 4.73828125],
         [ 8.71875   ],
         [ 9.96484375],
         [ 9.46484375],
         [ 6.9765625 ],
         [ 4.23828125],
         [ 5.9765625 ],
         [ 6.4765625 ],
         [ 9.71484375],
         [ 9.21484375],
         [ 6.7265625 ],
         [ 0.        ],
         [ 0.        ],
         [ 0.        ],
         [ 0.        ]]), array([[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 1.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.]])], [array([[  0.        ],
         [  0.        ],
         [  0.        ],
         [  0.        ],
         [  0.91015625],
         [  3.828125  ],
         [  5.67

In [36]:
net1.evaluate(randomTests)

0.85

In [34]:
np.array(randomTests[0][0]).shape

(28, 1)

In [40]:
net1.forward_prop(np.array(randomTests[0][0]).reshape(28,1))

array([[  2.44157640e-02],
       [  3.81715558e-06],
       [  2.53310181e-01],
       [  1.47181416e-01],
       [  6.59636212e-04],
       [  2.90603235e-01],
       [  9.41667579e-04],
       [  3.18882581e-04],
       [  7.94979132e-03],
       [  1.24435196e-04]])

In [49]:
X_test = n.test[0]
X_test.shape

(10000, 784)

In [46]:
n.test[0].shape

(10000, 784)

In [71]:
# Test data from mnist, max pooled

X1_test = np.zeros((10000,28))
for i in range(10000):
    for j in range(28):
        X1_test[i][j] = sum(X_test[i][28*j:28*j+28])
        
X1_test

array([[ 0.        ,  0.        ,  0.        , ...,  3.46875   ,
         2.34375   ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  2.44140625,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  2.6875    , ...,  0.        ,
         0.        ,  0.        ]])

In [55]:
# Test data labels from mnist, adjusted for correct output
y_test = n.test[1]
y1_test = np.zeros((10000,10))
for i in range(10000):
    y1_test[i][y_test[i]] = 1
    
y1_test

array([[ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [77]:
tests = [[np.array(X1_test[i]).reshape(28,1),np.array(y1_test[i]).reshape(10,1)] for i in range(10000)]
tests

[[array([[  0.        ],
         [  0.        ],
         [  0.        ],
         [  0.        ],
         [  0.        ],
         [  0.        ],
         [  0.        ],
         [  2.63671875],
         [ 12.83203125],
         [ 12.20703125],
         [  3.8046875 ],
         [  2.19921875],
         [  2.31640625],
         [  2.59765625],
         [  2.4375    ],
         [  2.26171875],
         [  2.03125   ],
         [  2.1953125 ],
         [  2.43359375],
         [  2.578125  ],
         [  2.7890625 ],
         [  2.43359375],
         [  2.44140625],
         [  2.70703125],
         [  3.37109375],
         [  3.46875   ],
         [  2.34375   ],
         [  0.        ]]), array([[ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 0.],
         [ 1.],
         [ 0.],
         [ 0.]])], [array([[  0.        ],
         [  0.        ],
         [  0.        ],
         [  4.55078125],
         [  7.55859375],
         [  8

In [78]:
net1.evaluate(tests)

0.7962

In [75]:
tests[0][0].shape

(28,)

In [63]:
y1_test.shape

(10000, 10)

In [65]:
X1_test[0]

array([  0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   2.63671875,
        12.83203125,  12.20703125,   3.8046875 ,   2.19921875,
         2.31640625,   2.59765625,   2.4375    ,   2.26171875,
         2.03125   ,   2.1953125 ,   2.43359375,   2.578125  ,
         2.7890625 ,   2.43359375,   2.44140625,   2.70703125,
         3.37109375,   3.46875   ,   2.34375   ,   0.        ])

In [66]:
np.argmax(y1_test[0])

7

In [74]:
net1.forward_prop(tests[0][0])

array([[  3.51339747e-04,   3.03944704e-04,   3.90783765e-04,
          3.51339747e-04,   3.51327520e-04,   3.51339747e-04,
          3.51339747e-04,   3.90783765e-04,   3.51339747e-04,
          3.88041398e-04,   3.90783765e-04,   3.18454181e-04,
          4.55274476e-04,   3.51339747e-04,   4.78232832e-04,
          1.23306249e-04,   3.51339747e-04,   3.62560907e-04,
          3.90783765e-04,   3.51339726e-04,   3.51339747e-04,
          3.90783765e-04,   3.51339747e-04,   3.51339747e-04,
          1.08398118e-05,   3.51339747e-04,   1.08391171e-05,
          3.51339747e-04],
       [  4.52019231e-05,   1.02233192e-07,   8.10630523e-08,
          4.52019231e-05,   4.52079375e-05,   4.52019231e-05,
          4.52019231e-05,   8.10630523e-08,   4.52019231e-05,
          8.15926421e-08,   8.10630523e-08,   7.27777729e-05,
          4.35315130e-04,   4.52019231e-05,   4.62220964e-04,
          2.75429437e-07,   4.52019231e-05,   2.89589651e-04,
          8.10630523e-08,   4.52019330e-05,